### ISSUE TITLE
add links to footer

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#17]
We'd like to add links to:
- [ ] info.risd.edu
- [ ] risd.edu 

In the footer.

**Comment by cmiller02** [comment]
I was thinking yesterday, in terms of the Undergrad welcome site, that instead of having different "Contacts + Resources" pages for the different targeted populations that I'd rather point people to info.risd.edu - where they can find office information that is regularly being updated - rather than pages with office contact info reproduced that we'll have to maintain, and also as a great way to start to drive them to info as a platform.  I made note yesterday about asking about the possibility of having info in the footer - so great to hear that we're going this direction for Grad already. Thanks!
