### ISSUE TITLE
Main Nav - Add current page active state

### ISSUE THREAD

**Issue by mmarol** [risd/risd-graduate-welcome#18]
Change the color of the current page's nav item to the blue. This would involve changing the RISD logo to pink.

**Comment by room421** [comment]
Would this involve a shading of the specific top nav category when you're in a subpage of the category?

For example, when you're on http://welcomegrad.risd.edu/learning-environment/the-studio/, there's not an obvious cue that you're in **Learning Environment**. We can't rely on URLs since some browsers abbreviate them, and the breadcrumb down the page is subtle.

**Comment by mmarol** [comment]
Yes this would do exactly that. 

Is there a need for the relevant subpage to also be highlighted? For example, if you're on [http://welcomegrad.risd.edu/learning-environment/the-studio/](http://welcomegrad.risd.edu/learning-environment/the-studio/) should `Learning Environment` **and** `The studio` be highlighted, or is it find if only `Learning Environment` is highlighted?

**Comment by room421** [comment]
I'm comfortable with just the main category being highlighted, since that's always visible. @micahmicah do you agree?

**Comment by mmarol** [comment]
There is one problem that arises with our content structure when trying to do this. The stories live at /stories/, which doesn't have a nav item. Every other page is nested under a section, which is represented on the nav. 

The changes I've made to the setup highlights the current section, but highlights nothing when viewing a story.
